spring:
  profiles:
    active:
    - dev
   
---
spring:
  profiles: dev     #开发环境
  application: 
    name: eureka-dev
    
server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务    
---
spring:
  profiles: test   #测试环境
  application: 
    name: eureka-test
    
    
    
server:
  port: 7002


eureka:
  instance:
    hostname: eureka7002.com
  client:
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务    
#  请保存为UTF-8格式
