spring:
  profiles:
    active:
    - dev
server:
  port: 5001


spring:
  application:
    name: dept-provider
eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

    
---
spring:
  profiles: dev     #开发环境
  
providerController:
  val: 5001dev



---    
spring:
  profiles: test    

providerController:
  val: 5001test